#! /bin/sh

[ $# -ne 1 ] && exit 1

status_fifo=$1

# sxhkd creates the fifo; wait for it in case this script starts first.
until [ -p "$status_fifo" ] ; do sleep 0.1 ; done

{ while read -r line ; do 
    msg=${line#?}
    case $line in
        H*)
            duration=2000
            ;;
        C*)
            duration=4000
            ;;
        T*)
            duration=1000
            ;;
    esac
    notify-send -t $duration "$msg"
done } < "$status_fifo"
