'\" t
.\"     Title: sxhkd
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/17/2026
.\"    Manual: Sxhkd Manual
.\"    Source: Sxhkd 0.7.3
.\"  Language: English
.\"
.TH "SXHKD" "1" "09/17/2026" "Sxhkd 0\&.7\&.3" "Sxhkd Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sxhkd \- Simple X hotkey daemon
.SH "SYNOPSIS"
.sp
\fBsxhkd\fR [\fIOPTIONS\fR] [\fIEXTRA_CONFIG\fR \&...]
.SH "DESCRIPTION"
.sp
sxhkd is a simple X hotkey daemon with a powerful and compact configuration syntax\&.
.SH "OPTIONS"
.sp
Every option has a short and a long form\&. Long options take their value as \fB\-\-name\fR=\fIVALUE\fR or \fB\-\-name\fR \fIVALUE\fR; \fB\-\-\fR ends the options, and any other argument is an extra configuration file\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print the help to standard output and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print the version information to standard output and exit\&.
.RE
.PP
\fB\-m\fR, \fB\-\-mapping\-count\fR \fICOUNT\fR
.RS 4
Handle the first
\fICOUNT\fR
mapping notify events\&.
.RE
.PP
\fB\-t\fR, \fB\-\-timeout\fR \fISECONDS\fR
.RS 4
Timeout in seconds for the recording of chord chains\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\fR \fIFILE\fR
.RS 4
Read the main configuration from the given file\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\fR \fIFILE\fR
.RS 4
Redirect the commands output to the given file\&.
.RE
.PP
\fB\-s\fR, \fB\-\-status\-fifo\fR \fIPATH\fR
.RS 4
Output status information to the given FIFO (see the
\fIStatus FIFO\fR
section)\&. The FIFO is created if it does not exist\&.
.RE
.PP
\fB\-a\fR, \fB\-\-abort\-keysym\fR \fIKEYSYM\fR
.RS 4
Name of the keysym used for aborting chord chains\&.
.RE
.PP
\fB\-i\fR, \fB\-\-indicator\fR \fIPOSITION\fR
.RS 4
Show an on\-screen indicator while a chord chain is in progress, anchored at the given
\fIPOSITION\fR
of the screen:
\fItop\fR,
\fItop\-left\fR,
\fItop\-right\fR,
\fIcenter\fR,
\fIcenter\-left\fR,
\fIcenter\-right\fR,
\fIbottom\fR,
\fIbottom\-left\fR
or
\fIbottom\-right\fR\&.
.RE
.PP
\fB\-f\fR, \fB\-\-indicator\-font\fR \fIFONT\fR
.RS 4
Font of the chain indicator, as a Pango font description (default:
\fImonospace 14\fR)\&. Only meaningful with
\fB\-i\fR\&.
.RE
.PP
\fB\-F\fR, \fB\-\-indicator\-foreground\fR \fICOLOR\fR
.RS 4
Foreground color of the chain indicator, as
\fI#rrggbb\fR
or
\fI#rrggbbaa\fR
(default:
\fI#ffffff\fR)\&. Only meaningful with
\fB\-i\fR\&.
.RE
.PP
\fB\-B\fR, \fB\-\-indicator\-background\fR \fICOLOR\fR
.RS 4
Background color of the chain indicator, as
\fI#rrggbb\fR
or
\fI#rrggbbaa\fR
(default:
\fI#222222\fR)\&. Only meaningful with
\fB\-i\fR\&.
.RE
.SH "BEHAVIOR"
.sp
\fBsxhkd\fR is a daemon that listens to keyboard events and execute commands\&.
.sp
It reads its configuration file from \fB$XDG_CONFIG_HOME/sxhkd/sxhkdrc\fR by default, or from the given file if the \fB\-c\fR option is used\&.
.sp
Additional configuration files can be passed as arguments\&.
.sp
If \fBsxhkd\fR receives a \fISIGUSR1\fR (resp\&. \fISIGUSR2\fR) signal, it will reload its configuration file (resp\&. toggle the grabbing state of all its bindings)\&. Both signals also end the chord chain in progress, if any\&.
.sp
If \fBsxhkd\fR recieves a \fISIGALRM\fR signal, it will break the current chain if there is one in progress\&.
.sp
With the \fB\-i\fR option, \fBsxhkd\fR shows a small window while a chord chain is in progress\&. It lists the chords received so far, separated by semicolons, and ends with a semicolon when the chain is waiting for its next chord or with a colon when the chain is locked (see below)\&. The window disappears when the chain ends, whether because its last chord was received, the abort keysym was pressed or the timeout was reached\&. It never takes the keyboard focus, lets pointer events through, and follows changes of the screen size\&. Translucent colors (an alpha below \fIff\fR) need a compositing manager; without one they render darker and fully transparent areas black, and \fBsxhkd\fR warns at startup\&.
.sp
The commands are executed via \fBSHELL\fR \fI\-c\fR \fBCOMMAND\fR (hence you can use environment variables)\&.
.sp
\fBSHELL\fR will be the content of the first defined environment variable in the following list: \fBSXHKD_SHELL\fR, \fBSHELL\fR\&.
.sp
\fBSXHKD_PID\fR will be automatically set to the pid of \fBsxhkd\fR in processes spawned by \fBsxhkd\fR, which may be used by the child process to send easily signals such as \fISIGALRM\fR to the correct instance of \fBsxhkd\fR\&.
.sp
If you have a non\-QWERTY keyboard or a non\-standard layout configuration, you should provide a \fICOUNT\fR of \fI1\fR to the \fB\-m\fR option or \fI\-1\fR (interpreted as infinity) if you constantly switch from one layout to the other (\fBsxhkd\fR ignores all mapping notify events by default because the majority of those events are pointless)\&.
.SH "STATUS FIFO"
.sp
With the \fB\-s\fR option, \fBsxhkd\fR reports what it is doing to a named pipe, so that an external program (a notification script, a status bar, \&...) can display the chord chain in progress or react to the commands being run\&.
.sp
\fBsxhkd\fR creates the pipe, readable and writable by its owner only, if nothing exists at the path, and removes it at exit in that case; a pipe that already exists is used as it is and left in place\&. Anything else at the path, or a pipe that cannot be created or opened, is a startup error\&. \fBsxhkd\fR opens the pipe for reading and writing in non\-blocking mode, so it starts even when nobody is reading yet and never stalls on the pipe\&. Messages written while nobody is reading are kept by the pipe until it is full, and are dropped afterwards\&.
.sp
Each message is a single line made of a one\-character prefix followed by a text:
.sp
.if n \{\
.RS 4
.\}
.nf
PREFIX  WHEN                                        TEXT
H       a chord was received                        the chords received so far
B       a chord chain has begun                     Begin chain
E       the chord chain has ended                   End chain
T       the chord chain timed out                   Timeout reached
C       a command has been started                  the command
.fi
.if n \{\
.RE
.\}
.sp
The text of an \fIH\fR message is the list of the chords received since the chain began, separated by semicolons, each one written as in the configuration file (modifiers, \fB~\fR and \fB@\fR included)\&. Every chord that matches a hotkey produces an \fIH\fR message, including the only chord of a single\-chord hotkey\&. In a locked chain, every chord received after the lock produces an \fIH\fR message made of the locked prefix and that chord; the prefix itself never grows\&.
.sp
\fIB\fR is sent after the \fIH\fR message of the first chord of a chain, and \fIE\fR is sent whenever the chain ends: after its last chord, when the abort keysym is pressed, when the timeout is reached (in which case a \fIT\fR message precedes it), or when \fBsxhkd\fR reloads its configuration or ungrabs its bindings while a chain is in progress\&. \fIC\fR is sent after the command has been started, and after the \fIE\fR message when the command ends a chain\&.
.sp
For example, given the two hotkeys
.sp
.if n \{\
.RS 4
.\}
.nf
super + a
    xterm

super + m ; h
    echo H
.fi
.if n \{\
.RE
.\}
.sp
pressing \fIsuper + a\fR produces:
.sp
.if n \{\
.RS 4
.\}
.nf
Hsuper + a
Cxterm
.fi
.if n \{\
.RE
.\}
.sp
and pressing \fIsuper + m\fR then \fIh\fR produces:
.sp
.if n \{\
.RS 4
.\}
.nf
Hsuper + m
BBegin chain
Hsuper + m;h
EEnd chain
Cecho H
.fi
.if n \{\
.RE
.\}
.sp
A minimal consumer starts \fBsxhkd\fR on a pipe, waits for the pipe to appear, and reads it line by line, stripping the prefix:
.sp
.if n \{\
.RS 4
.\}
.nf
sxhkd \-s "$XDG_RUNTIME_DIR/sxhkd\&.fifo" &
until [ \-p "$XDG_RUNTIME_DIR/sxhkd\&.fifo" ]; do sleep 0\&.1; done

while read \-r line; do
    case $line in
        H*) notify\-send \-t 2000 "sxhkd" "${line#?}" ;;
        C*) notify\-send \-t 4000 "sxhkd" "Running: ${line#?}" ;;
        T*) notify\-send \-t 1000 "sxhkd" "Chain timed out" ;;
    esac
done < "$XDG_RUNTIME_DIR/sxhkd\&.fifo"
.fi
.if n \{\
.RE
.\}
.sp
The \fBexamples/notification\fR directory of the source distribution contains a complete setup along these lines\&.
.SH "CONFIGURATION"
.sp
Each line of the configuration file is interpreted as so:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If it is empty or starts with
#, it is ignored\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If it starts with a space, it is read as a command\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Otherwise, it is read as a hotkey\&.
.RE
.sp
General syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
HOTKEY
    [;]COMMAND

HOTKEY      := CHORD_1 ; CHORD_2 ; \&... ; CHORD_n
CHORD_i     := [MODIFIERS_i +] [~][@]KEYSYM_i
MODIFIERS_i := MODIFIER_i1 + MODIFIER_i2 + \&... + MODIFIER_ik
.fi
.if n \{\
.RE
.\}
.sp
The valid modifier names are: \fIsuper\fR, \fIhyper\fR, \fImeta\fR, \fIalt\fR, \fIcontrol\fR, \fIctrl\fR, \fIshift\fR, \fImode_switch\fR, \fIlock\fR, \fImod1\fR, \fImod2\fR, \fImod3\fR, \fImod4\fR, \fImod5\fR and \fIany\fR\&.
.sp
The keysym names are given by the output of \fBxev \-event keyboard\fR\&.
.sp
Hotkeys and commands can be spread across multiple lines by ending each partial line with a backslash character\&.
.sp
When multiple chords are separated by semicolons, the hotkey is a chord chain: the command will only be executed after receiving each chord of the chain in consecutive order\&.
.sp
The colon character can be used instead of the semicolon to indicate that the chord chain shall not be aborted when the chain tail is reached\&.
.sp
If a command starts with a semicolon, it will be executed synchronously, otherwise asynchronously\&.
.sp
The \fIEscape\fR key can be used to abort a chord chain\&.
.sp
If \fB@\fR is added at the beginning of the keysym, the command will be run on key release events, otherwise on key press events\&.
.sp
If \fB~\fR is added at the beginning of the keysym, the captured event will be replayed for the other clients\&.
.sp
Pointer hotkeys can be defined by using one of the following special keysym names: \fIbutton1\fR, \fIbutton2\fR, \fIbutton3\fR, \&..., \fIbutton24\fR\&.
.sp
The hotkey and the command may contain sequences of the form \fI{STRING_1,\&...,STRING_N}\fR\&. Braces can be escaped with \fB\e\fR\&.
.sp
In addition, the sequences can contain ranges of the form \fIA\fR\-\fIZ\fR where \fIA\fR and \fIZ\fR are alphanumeric characters\&.
.sp
The underscore character represents an empty sequence element\&.
.SH "AUTHOR"
.sp
Bastien Dejean <nihilhill at gmail\&.com>
.SH "MAILING LIST"
.sp
sxhkd at librelist\&.com
