:man source:   Sxhkd
:man version:  {revnumber}
:man manual:   Sxhkd Manual

sxhkd(1)
========

Name
----

sxhkd - Simple X hotkey daemon

Synopsis
--------

*sxhkd* [_OPTIONS_] [_EXTRA_CONFIG_ …]

Description
-----------

sxhkd is a simple X hotkey daemon with a powerful and compact configuration syntax.

Options
-------


*-h*::
    Print the synopsis to standard output and exit.

*-v*::
    Print the version information to standard output and exit.

*-m* _COUNT_::
    Handle the first _COUNT_ mapping notify events.

*-t* _TIMEOUT_::
    Timeout in seconds for the recording of chord chains.

*-c* _CONFIG_FILE_::
    Read the main configuration from the given file.

*-r* _REDIR_FILE_::
    Redirect the commands output to the given file.

*-s* _STATUS_FIFO_::
    Output status information to the given FIFO (see the _Status FIFO_ section). The FIFO must already exist.

*-a* _ABORT_KEYSYM_::
    Name of the keysym used for aborting chord chains.

*-i* _POSITION_::
    Show an on-screen indicator while a chord chain is in progress, anchored at the given _POSITION_ of the screen: _top-left_, _top-right_, _bottom-left_, _bottom-right_ or _center_.

*-f* _FONT_::
    Font of the chain indicator, as a Pango font description (default: _monospace 14_). Only meaningful with *-i*.

*-F* _COLOR_::
    Foreground color of the chain indicator, as _#rrggbb_ (default: _#ffffff_). Only meaningful with *-i*.

*-B* _COLOR_::
    Background color of the chain indicator, as _#rrggbb_ (default: _#222222_). Only meaningful with *-i*.


Behavior
--------

*sxhkd* is a daemon that listens to keyboard events and execute commands.

It reads its configuration file from *$XDG_CONFIG_HOME/sxhkd/sxhkdrc* by default, or from the given file if the *-c* option is used.

Additional configuration files can be passed as arguments.

If *sxhkd* receives a _SIGUSR1_ (resp. _SIGUSR2_) signal, it will reload its configuration file (resp. toggle the grabbing state of all its bindings). Both signals also end the chord chain in progress, if any.

If *sxhkd* recieves a _SIGALRM_ signal, it will break the current chain if there is one in progress.

With the *-i* option, *sxhkd* shows a small window while a chord chain is in progress. It lists the chords received so far, separated by semicolons, and ends with a semicolon when the chain is waiting for its next chord or with a colon when the chain is locked (see below). The window disappears when the chain ends, whether because its last chord was received, the abort keysym was pressed or the timeout was reached. It never takes the keyboard focus.

The commands are executed via *SHELL* _-c_ *COMMAND* (hence you can use environment variables).

*SHELL* will be the content of the first defined environment variable in the following list: *SXHKD_SHELL*, *SHELL*.

*SXHKD_PID* will be automatically set to the pid of *sxhkd* in processes spawned by *sxhkd*, which may be used by the child process to send easily signals such as _SIGALRM_ to the correct instance of *sxhkd*.

If you have a non-QWERTY keyboard or a non-standard layout configuration, you should provide a _COUNT_ of _1_ to the *-m* option or _-1_ (interpreted as infinity) if you constantly switch from one layout to the other (*sxhkd* ignores all mapping notify events by default because the majority of those events are pointless).


Status FIFO
-----------

With the *-s* option, *sxhkd* reports what it is doing to a named pipe, so that an external program (a notification script, a status bar, …) can display the chord chain in progress or react to the commands being run.

The pipe must be created beforehand, for instance with *mkfifo*. *sxhkd* opens it for reading and writing in non-blocking mode, so it starts even when nobody is reading yet and never stalls on the pipe; if the pipe cannot be opened, a warning is printed and no status is reported. Messages written while nobody is reading are kept by the pipe until it is full, and are dropped afterwards.

Each message is a single line made of a one-character prefix followed by a text:

----
PREFIX  WHEN                                        TEXT
H       a chord was received                        the chords received so far
B       a chord chain has begun                     Begin chain
E       the chord chain has ended                   End chain
T       the chord chain timed out                   Timeout reached
C       a command has been started                  the command
----

The text of an _H_ message is the list of the chords received since the chain began, separated by semicolons, each one written as in the configuration file (modifiers, *~* and *@* included). Every chord that matches a hotkey produces an _H_ message, including the only chord of a single-chord hotkey. In a locked chain, every chord received after the lock produces an _H_ message made of the locked prefix and that chord; the prefix itself never grows.

_B_ is sent after the _H_ message of the first chord of a chain, and _E_ is sent whenever the chain ends: after its last chord, when the abort keysym is pressed, when the timeout is reached (in which case a _T_ message precedes it), or when *sxhkd* reloads its configuration or ungrabs its bindings while a chain is in progress. _C_ is sent after the command has been started, and after the _E_ message when the command ends a chain.

For example, given the two hotkeys

----
super + a
    xterm

super + m ; h
    echo H
----

pressing _super + a_ produces:

----
Hsuper + a
Cxterm
----

and pressing _super + m_ then _h_ produces:

----
Hsuper + m
BBegin chain
Hsuper + m;h
EEnd chain
Cecho H
----

A minimal consumer creates the pipe, starts *sxhkd* on it, and reads it line by line, stripping the prefix:

----
mkfifo "$XDG_RUNTIME_DIR/sxhkd.fifo"
sxhkd -s "$XDG_RUNTIME_DIR/sxhkd.fifo" &

while read -r line; do
    case $line in
        H*) notify-send -t 2000 "sxhkd" "${line#?}" ;;
        C*) notify-send -t 4000 "sxhkd" "Running: ${line#?}" ;;
        T*) notify-send -t 1000 "sxhkd" "Chain timed out" ;;
    esac
done < "$XDG_RUNTIME_DIR/sxhkd.fifo"
----

The *examples/notification* directory of the source distribution contains a complete setup along these lines.

Configuration
-------------

Each line of the configuration file is interpreted as so:

* If it is empty or starts with `#`, it is ignored.
* If it starts with a space, it is read as a command.
* Otherwise, it is read as a hotkey.

General syntax:

----
HOTKEY
    [;]COMMAND

HOTKEY      := CHORD_1 ; CHORD_2 ; … ; CHORD_n
CHORD_i     := [MODIFIERS_i +] [~][@]KEYSYM_i
MODIFIERS_i := MODIFIER_i1 + MODIFIER_i2 + … + MODIFIER_ik
----

The valid modifier names are: _super_, _hyper_, _meta_, _alt_, _control_, _ctrl_, _shift_, _mode_switch_, _lock_, _mod1_, _mod2_, _mod3_, _mod4_, _mod5_ and _any_.

The keysym names are given by the output of *xev -event keyboard*.

Hotkeys and commands can be spread across multiple lines by ending each partial line with a backslash character.

When multiple chords are separated by semicolons, the hotkey is a chord chain: the command will only be executed after receiving each chord of the chain in consecutive order.

The colon character can be used instead of the semicolon to indicate that the chord chain shall not be aborted when the chain tail is reached.

If a command starts with a semicolon, it will be executed synchronously, otherwise asynchronously.

The _Escape_ key can be used to abort a chord chain.

If *@* is added at the beginning of the keysym, the command will be run on key release events, otherwise on key press events.

If *~* is added at the beginning of the keysym, the captured event will be replayed for the other clients.

Pointer hotkeys can be defined by using one of the following special keysym names: _button1_, _button2_, _button3_, …, _button24_.

The hotkey and the command may contain sequences of the form '{STRING_1,…,STRING_N}'. Braces can be escaped with *\*.

In addition, the sequences can contain ranges of the form _A_-_Z_ where _A_ and _Z_ are alphanumeric characters.

The underscore character represents an empty sequence element.

Author
------

Bastien Dejean <nihilhill at gmail.com>

Mailing List
------------

sxhkd at librelist.com

////
vim: set ft=asciidoc:
////
